### ISSUE TITLE
关于unsupervised下的mvtec指标

### ISSUE THREAD

**Issue by SSRheart** [CASIA-IVA-Lab/AnomalyGPT#12]
请问Table3中，anomalyGPT的acc指标是在什么条件下得到的？是few-shot嘛，还是用zero-shot

**Comment by FantasticGNU** [comment]
table3 的结果是在 mvtec 数据集上无监督训练得到的，即使用 mvtec 数据集中的【正常样本】训练模型，然后在 mvtec 的测试集上测试。

**Comment by SSRheart** [comment]
> table3 的结果是在 mvtec 数据集上无监督训练得到的，即使用 mvtec 数据集中的【正常样本】训练模型，然后在 mvtec 的测试集上测试。

请问测试的时候使用test_mvtec.py，应该选择用few-shot的参数嘛？

**Comment by FantasticGNU** [comment]
如果你想复现table3的结果，那么应该加载在 mvtec 数据集上训练的模型参数并且不使用 few-shot 参数。

**Comment by SSRheart** [comment]
感谢回复，已经能够成功复现table3结果
