### ISSUE TITLE
vicuna_0 模型

### ISSUE THREAD

**Issue by liuxuannan** [CASIA-IVA-Lab/AnomalyGPT#13]
我在将llama模型和vicuna_delta_7b_0合成vicuna模型时，出现下面错误The size of tensor a (32000) must match the size of tensor b (32001) at non-singleton dimension 0，想问下现在v0版本是不可用了吗？就是如果合成了v1.1版本对最终的anomalyCPT模型会有影响吗

**Comment by FantasticGNU** [comment]
你需要安装 <=1.10.0 版本的 FastChat 来合并参数，参考https://github.com/lm-sys/FastChat/blob/main/docs/vicuna_weights_version.md，v1.1版本的对话起止符号与v0不同，可能会有影响
