### ISSUE TITLE
关于文章的实验结果

### ISSUE THREAD

**Issue by 18894269590** [CASIA-IVA-Lab/AnomalyGPT#15]
作者：
       您好！我看到您的模型结构中，除了Prompt Learner和LLM之外，都与APRIL-GAN是一样的，为什么表二的评价结果中，没有APRIL-GAN的对比结果，而且所测量的指标表面上看和后续您添加的模块没有直接的关系，好像应该和APRIL-GAN的指标一样的，但是，却比该论文的要高，请问这是什么原因，或者能否更清楚的阐释其中的原因，谢谢。

**Comment by zhangzilongc** [comment]
> 作者： 您好！我看到您的模型结构中，除了Prompt Learner和LLM之外，都与APRIL-GAN是一样的，为什么表二的评价结果中，没有APRIL-GAN的对比结果，而且所测量的指标表面上看和后续您添加的模块没有直接的关系，好像应该和APRIL-GAN的指标一样的，但是，却比该论文的要高，请问这是什么原因，或者能否更清楚的阐释其中的原因，谢谢。

没有prompt tuning部分就一样了，文章实验部分few-shot实验设置不是很清楚，主要参考的方法（APRIL-GAN）结果没有写。不知道是不是我没看懂，few-shot的方法难道本质不就是个多层特征的patchcore吗，few-shot部分和unsupervised部分有重叠吗，为什么比patchcore高这么多呢，另外比较的实验，并没有统一 image encoder的backbone，这样的对比公平吗

**Comment by FantasticGNU** [comment]
> 作者： 您好！我看到您的模型结构中，除了Prompt Learner和LLM之外，都与APRIL-GAN是一样的，为什么表二的评价结果中，没有APRIL-GAN的对比结果，而且所测量的指标表面上看和后续您添加的模块没有直接的关系，好像应该和APRIL-GAN的指标一样的，但是，却比该论文的要高，请问这是什么原因，或者能否更清楚的阐释其中的原因，谢谢。

1. 我们的 LLM 和 prompt learner 也会回传梯度到 Image Decoder 中，用文本信息指导 Image Decoder 更新参数，以得到更准确的结果，这些模块之间是有关系和相互影响的。
2. APRIL GAN 是有监督训练的，在训练期间见过真实的异常样本，而我们的方法是无监督训练的，在训练期间只使用了正常样本和异常模拟，所以会有结果差异，而且没有和APRIL-GAN进行性能对比（因为实验设置不一样）。
3. APRIL GAN 仍然属于传统的异常检测方法，即只能提供异常检测分数而无法做出判断，需要人工设置阈值，本文的主要特点和贡献是利用LLM解决了这个分数和阈值问题，而且能够提供对图像内容的详细描述，利用了大型语言模型的强大先验知识。

**Comment by FantasticGNU** [comment]
> 没有prompt tuning部分就一样了，文章实验部分few-shot实验设置不是很清楚，主要参考的方法（APRIL-GAN）结果没有写。不知道是不是我没看懂，few-shot的方法难道本质不就是个多层特征的patchcore吗，few-shot部分和unsupervised部分有重叠吗，为什么比patchcore高这么多呢，另外比较的实验，并没有统一 image encoder的backbone，这样的对比公平吗

1. Few-shot 实验部分，我们是在 mvtec 和 visa 两个数据机上进行交叉实验的，即在 visa 上训练的模型在 mvtec 上进行 few-shot 测试，反之亦然。
2. Few-shot 的方法确实是一个多层特征的 patchCore，我们参考了 APRIL-GAN 的设计，性能提升应该和多层级特征、backbone 等都有关系。
3. 没有统一 image encoder 的 backbone 方面，不同的异常检测方法中采用了各种不同的 backbone，之前的方法如 WinCLIP（CVPR2023）、APRIL-GAN 等也是采用同样的方法进行性能对比的，我们和他们的对比方式保持了一致。

**Comment by zhangzilongc** [comment]
> > 没有prompt tuning部分就一样了，文章实验部分few-shot实验设置不是很清楚，主要参考的方法（APRIL-GAN）结果没有写。不知道是不是我没看懂，few-shot的方法难道本质不就是个多层特征的patchcore吗，few-shot部分和unsupervised部分有重叠吗，为什么比patchcore高这么多呢，另外比较的实验，并没有统一 image encoder的backbone，这样的对比公平吗
> 
> 1. Few-shot 实验部分，我们是在 mvtec 和 visa 两个数据机上进行交叉实验的，即在 visa 上训练的模型在 mvtec 上进行 few-shot 测试，反之亦然。
> 2. Few-shot 的方法确实是一个多层特征的 patchCore，我们参考了 APRIL-GAN 的设计，性能提升应该和多层级特征、backbone 等都有关系。
> 3. 没有统一 image encoder 的 backbone 方面，不同的异常检测方法中采用了各种不同的 backbone，之前的方法如 WinCLIP（CVPR2023）、APRIL-GAN 等也是采用同样的方法进行性能对比的，我们和他们的对比方式保持了一致。

谢谢！还是希望把第一个那个写清楚一些，看的时候有的有点懵

**Comment by FantasticGNU** [comment]
我们在论文的 introduction 中介绍实验时说明了这个设置，之后会在实验部分中再次补充说明，谢谢您的建议。

**Comment by 18894269590** [comment]
> > 作者： 您好！我看到您的模型结构中，除了Prompt Learner和LLM之外，都与APRIL-GAN是一样的，为什么表二的评价结果中，没有APRIL-GAN的对比结果，而且所测量的指标表面上看和后续您添加的模块没有直接的关系，好像应该和APRIL-GAN的指标一样的，但是，却比该论文的要高，请问这是什么原因，或者能否更清楚的阐释其中的原因，谢谢。
> 
> 1. 我们的 LLM 和 prompt learner 也会回传梯度到 Image Decoder 中，用文本信息指导 Image Decoder 更新参数，以得到更准确的结果，这些模块之间是有关系和相互影响的。
> 2. APRIL GAN 是有监督训练的，在训练期间见过真实的异常样本，而我们的方法是无监督训练的，在训练期间只使用了正常样本和异常模拟，所以会有结果差异，而且没有和APRIL-GAN进行性能对比（因为实验设置不一样）。
> 3. APRIL GAN 仍然属于传统的异常检测方法，即只能提供异常检测分数而无法做出判断，需要人工设置阈值，本文的主要特点和贡献是利用LLM解决了这个分数和阈值问题，而且能够提供对图像内容的详细描述，利用了大型语言模型的强大先验知识。
谢谢您的回复，您在增加了 LLM 和 prompt learner 后，损失函数看起来和APRIL GAN还是一样的，并没有增加与 LLM部分输出有关的损失函数部分，所以，很疑惑prompt learner 是如何训练的，而且文章的结果指标都是针对分类分割的，也都是不需要固定阈值的，如何说明您工作的价值和意义；关于结果指标，和APRIL GAN的区别除了您使用了伪缺陷样本，其他的好像是一样的，因为APRIL GAN也在训练 Decoder。谢谢，可以加个微信吗(微信号:wangqishan10)。

**Comment by zhangzilongc** [comment]
> > > 作者： 您好！我看到您的模型结构中，除了Prompt Learner和LLM之外，都与APRIL-GAN是一样的，为什么表二的评价结果中，没有APRIL-GAN的对比结果，而且所测量的指标表面上看和后续您添加的模块没有直接的关系，好像应该和APRIL-GAN的指标一样的，但是，却比该论文的要高，请问这是什么原因，或者能否更清楚的阐释其中的原因，谢谢。
> > 
> > 
> > 
> > 1. 我们的 LLM 和 prompt learner 也会回传梯度到 Image Decoder 中，用文本信息指导 Image Decoder 更新参数，以得到更准确的结果，这些模块之间是有关系和相互影响的。
> > 2. APRIL GAN 是有监督训练的，在训练期间见过真实的异常样本，而我们的方法是无监督训练的，在训练期间只使用了正常样本和异常模拟，所以会有结果差异，而且没有和APRIL-GAN进行性能对比（因为实验设置不一样）。
> > 3. APRIL GAN 仍然属于传统的异常检测方法，即只能提供异常检测分数而无法做出判断，需要人工设置阈值，本文的主要特点和贡献是利用LLM解决了这个分数和阈值问题，而且能够提供对图像内容的详细描述，利用了大型语言模型的强大先验知识。
> 
> 谢谢您的回复，您在增加了 LLM 和 prompt learner 后，损失函数看起来和APRIL GAN还是一样的，并没有增加与 LLM部分输出有关的损失函数部分，所以，很疑惑prompt learner 是如何训练的，而且文章的结果指标都是针对分类分割的，也都是不需要固定阈值的，如何说明您工作的价值和意义；关于结果指标，和APRIL GAN的区别除了您使用了伪缺陷样本，其他的好像是一样的，因为APRIL GAN也在训练 Decoder。谢谢，可以加个微信吗(微信号:wangqishan10)。

是用了cross entropy文本的token对齐分类训练的prompt learner，用这个部分的损失去影响decoder部分。里面有个图像级别的accuracy是说明不需要阈值设定，而之前方法如果固定阈值精度会低。

**Comment by 18894269590** [comment]
这个损失还得再找一下，听你的意思感觉是交叉熵训练了输出文本和其真值训练了prompt learner。
