### ISSUE TITLE
运行维度失败

### ISSUE THREAD

**Issue by xyh2211** [CASIA-IVA-Lab/AnomalyGPT#18]
你好，请问为什么运行前向传播的时候显示Llamaforcausallm.from_pertrained(vicuna_ckpt_path)这一块有错误，显示维度不对应，跑的标准数据集，还有能不能将线上运行重新上线一下，挂掉了

**Comment by FantasticGNU** [comment]
感谢关注！前面的报错请提供更详细的信息，另外线上demo已经修好了。
