### ISSUE TITLE
AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * gradient_acc_step * world_size 16 != 1 * 8 * 1

### ISSUE THREAD

**Issue by William9Baker** [CASIA-IVA-Lab/AnomalyGPT#19]
This error occurs in deepspeed.

**Comment by IESSTTJP** [comment]
> ```
>     self.ds_engine, self.optimizer, _ , _ = deepspeed.initialize(
>         model=self.model, 
>         model_parameters=self.model.parameters(),
>         config_params=ds_params, 
>         dist_init_required=True,
>         args=types.SimpleNamespace(**args)
>     )
> ```

您好请问一下这个是怎么解决的

**Comment by maoning123ab** [comment]
请问您是怎么解决这个问题的
