### ISSUE TITLE
Few shot training configuration

### ISSUE THREAD

**Issue by chihhuiho** [CASIA-IVA-Lab/AnomalyGPT#2]
Hi,
Thanks for the great work. The demo looks amazing. For the few shot experiment, I would like to ask whether the decoder and LLM are trained on the entire MVTec dataset or just the sampled few shot examples (e.g. 30 images for 2 shot)? If it is the latter, could you provide the checkpoints for each shot (e.g. k=1, 2, 4)?
Thank you.

**Comment by FantasticGNU** [comment]
Our "few-shot inference" entails conducting inference on a particular class of objects that have never been seen during the training phase, with only few normal samples provided as references, so we do not need few-shot training. In the experiments of our paper, we unsupervisedly train our model on the Visa dataset, and employ this trained model directly for performing few-shot inference on the MVTec dataset. Conversely, models trained unsupervisedly on the MVTec dataset are employed for few-shot inference on the VisA dataset.


So if you want to test the few-shot inference effect of k=1,2,4 on the MVTec dataset, you can directly use the unsupervised training parameters on VisA dataset, and then set the value of "k_shot" in [./code/test_mvtec.py](https://github.com/CASIA-IVA-Lab/AnomalyGPT/blob/main/code/test_mvtec.py) to experiment.
