### ISSUE TITLE
关于运行内存报错，但多GPU并行无果

### ISSUE THREAD

**Issue by Anew1001** [CASIA-IVA-Lab/AnomalyGPT#20]
作者，你好
delta_ckpt = torch.load(args['delta_ckpt_path'], map_location=torch.device('cpu'))
model.load_state_dict(delta_ckpt, strict=False)
delta_ckpt = torch.load(args['anomalygpt_ckpt_path'], map_location=torch.device('cpu'))
model.load_state_dict(delta_ckpt, strict=False)
print(device)
model = model.eval().half().to(device)
最后一行，转移到GPU上运行，内存不足，但是设置多个GPU使用，仍然只有一个10.76G的GPU工作。可否给出一个解决方法或思路，谢谢
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/110953058/2c7a2f33-acf8-40a3-9fe0-10c4ec5a5dca)

**Comment by Anew1001** [comment]
os.environ["CUDA_VISIBLE_DEVICES"] = '0,1'
这样设置没用
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/110953058/a47e03ba-6e54-4d40-bd63-025d00f1a76d)
初次接触，望指点！

**Comment by en-53** [comment]
你好，可以问一下如何下载LLaMA的权重吗，我填了表但是没有得到回应
<img width="806" alt="image" src="https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/61526009/db088cf8-a9c5-4a28-bb4c-f46280568c6c">

**Comment by William9Baker** [comment]
> 你好，可以问一下如何下载LLaMA的权重吗，我填了表但是没有得到回应 <img alt="image" width="806" src="https://user-images.githubusercontent.com/61526009/268229364-db088cf8-a9c5-4a28-bb4c-f46280568c6c.png">

我也是，但后来找到了有其他方法可以下载

**Comment by Anew1001** [comment]
> 你好，可以问一下如何下载LLaMA的权重吗，我填了表但是没有得到回应 <img alt="image" width="806" src="https://user-images.githubusercontent.com/61526009/268229364-db088cf8-a9c5-4a28-bb4c-f46280568c6c.png">

https://huggingface.co/lmsys/vicuna-7b-delta-v0/tree/main这个网址里可以下

**Comment by en-53** [comment]
> > 你好，可以问一下如何下载LLaMA的权重吗，我填了表但是没有得到回应 <img alt="image" width="806" src="https://user-images.githubusercontent.com/61526009/268229364-db088cf8-a9c5-4a28-bb4c-f46280568c6c.png">
> 
> https://huggingface.co/lmsys/vicuna-7b-delta-v0/tree/main 这个网址里可以下

这个不是1.2里的Delta Weights吗，不过我从https://huggingface.co/decapoda-research/llama-7b-hf/tree/main看到可以下载权重，不清楚是不是1.1对应的那个，因为这里有33组

**Comment by Fritz-yuan** [comment]
> > > 你好，可以问一下如何下载LLaMA的权重吗，我填了表但是没有得到回应 <img alt="image" width="806" src="https://user-images.githubusercontent.com/61526009/268229364-db088cf8-a9c5-4a28-bb4c-f46280568c6c.png">
> > 
> > 
> > https://huggingface.co/lmsys/vicuna-7b-delta-v0/tree/main 这个网址里可以下
> 
> 这个不是1.2里的Delta Weights吗，不过我从https://huggingface.co/decapoda-research/llama-7b-hf/tree/main看到可以下载权重，不清楚是不是1.1对应的那个，因为这里有33组

你好，请问你成功下载LLaMA Weight了吗？顺便问一下是否可以直接使用https://huggingface.co/lmsys/vicuna-7b-v1.5这个链接下的vincuna model

**Comment by FantasticGNU** [comment]
> 作者，你好 delta_ckpt = torch.load(args['delta_ckpt_path'], map_location=torch.device('cpu')) model.load_state_dict(delta_ckpt, strict=False) delta_ckpt = torch.load(args['anomalygpt_ckpt_path'], map_location=torch.device('cpu')) model.load_state_dict(delta_ckpt, strict=False) print(device) model = model.eval().half().to(device) 最后一行，转移到GPU上运行，内存不足，但是设置多个GPU使用，仍然只有一个10.76G的GPU工作。可否给出一个解决方法或思路，谢谢 ![image](https://user-images.githubusercontent.com/110953058/267967979-2c7a2f33-acf8-40a3-9fe0-10c4ec5a

推理使用多 GPU 需要其他库的支持，如果 GPU 显存不够，可以考虑使用 CPU 推理，把 `code/web_demo.py` 和 `code/model/openllama.py` 等文件里面的 GPU 相关代码改成 CPU 的。

**Comment by weiweinorth** [comment]
> > > 你好，可以问一下如何下载LLaMA的权重吗，我填了表但是没有得到回应 <img alt="image" width="806" src="https://user-images.githubusercontent.com/61526009/268229364-db088cf8-a9c5-4a28-bb4c-f46280568c6c.png">
> > 
> > 
> > https://huggingface.co/lmsys/vicuna-7b-delta-v0/tree/main 这个网址里可以下
> 
> 这个不是1.2里的Delta Weights吗，不过我从https://huggingface.co/decapoda-research/llama-7b-hf/tree/main看到可以下载权重，不清楚是不是1.1对应的那个，因为这里有33组

请问又从https://huggingface.co/decapoda-research/llama-7b-hf/tree/main里下载成功了吗？
