### ISSUE TITLE
运行成功了

### ISSUE THREAD

**Issue by xyh2211** [CASIA-IVA-Lab/AnomalyGPT#22]
你好，可以成功运行了，但是每次运行启动时间都需要很长时间，调试一直等待，权重太大的原因吗

**Comment by William9Baker** [comment]
> 你好，可以成功运行了，但是每次运行启动时间都需要很长时间，调试一直等待，权重太大的原因吗

Congratulations！请问下，在初始化DeepSpeed引擎的时候一直报错，AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'，这个你有遇到过吗？

**Comment by William9Baker** [comment]
> > 你好，可以成功运行了，但是每次运行启动时间都需要很长时间，调试一直等待，权重太大的原因吗
> 
> Congratulations！请问下，在初始化DeepSpeed引擎的时候一直报错，AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'，这个你有遇到过吗？

问题已解决

**Comment by William9Baker** [comment]
您好，请问下您在复现时候，数据集是如何放置的呀？我理解的是MVTec-AD dataset和pre-training data of PandaGPT这两个数据集应该都要下载，那么如何放置呢？我是下面这样放置的，但是训练时候貌似不太对，望指教！谢谢！
data
|---pandagpt4_visual_instruction_data.json
|---images
|-----|----mvtec_anomaly_detection
|----------|-- bottle
|----------|-----|---- ground_truth
|----------|-----|----- test
|----------|-----|----- train
|-----|----images
|-----|-----|----- 000000124934.jpg
|-----|-----|----- 000000257414.jpg

**Comment by FantasticGNU** [comment]
> 你好，可以成功运行了，但是每次运行启动时间都需要很长时间，调试一直等待，权重太大的原因吗

对的，大模型都有这样的问题，加载权重需要很长的时间，这个没啥办法
