### ISSUE TITLE
如何下载LLaMA权重？

### ISSUE THREAD

**Issue by en-53** [CASIA-IVA-Lab/AnomalyGPT#25]
我在1.1. Obtain LLaMA Weights中填写了Meta AI的表格，但并没有得到回应，我在[https://huggingface.co/decapoda-research/llama-7b-hf/tree/main](https://github.com/CASIA-IVA-Lab/AnomalyGPT/issues/20)看到可以下载权重，但是不清楚是不是1.1对应的那个，因为这个链接里有33组权重，而Delta Weight只有两组

**Comment by William9Baker** [comment]
其他方法可以下载

**Comment by en-53** [comment]
> 其他方法可以下载

您好请问是什么呢，是我说的这个吗
![0651428E](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/61526009/75b6dc2c-ec2b-4d0d-a7e1-25710361a027)

**Comment by William9Baker** [comment]
> > 其他方法可以下载
> 
> 您好请问是什么呢，是我说的这个吗 ![0651428E](https://user-images.githubusercontent.com/61526009/268665761-75b6dc2c-ec2b-4d0d-a7e1-25710361a027.png)

你跟我邮箱（suifengingo@163.com)发个消息，我发你链接

**Comment by weiweinorth** [comment]
@William9Baker ，@en-53 ，

您好。请问可以发我一份链接到weiweiyanghe@gmail.com吗？

**Comment by mellody11** [comment]
@William9Baker @en-53 @weiweinorth 
您好，请问能否发我一份链接，谢谢了。
1846960330@qq.com

**Comment by twmht** [comment]
@William9Baker 
qrnnis2623891@gmail.com
麻煩發給我一份，謝謝

**Comment by EddieEduardo** [comment]
> > > 其他方法可以下载
> > 
> > 
> > 您好请问是什么呢，是我说的这个吗 ![0651428E](https://user-images.githubusercontent.com/61526009/268665761-75b6dc2c-ec2b-4d0d-a7e1-25710361a027.png)
> 
> 你跟我邮箱（[suifengingo@163.com](mailto:suifengingo@163.com))发个消息，我发你链接

您好，可否也发我一份链接，谢谢啦
everydayjoy0206@126.com

**Comment by LinPengyue** [comment]
> > > 其他方法可以下载
> > 
> > 
> > 你好请问是什么呢，我是这个吗？![0651428E](https://user-images.githubusercontent.com/61526009/268665761-75b6dc2c-ec2b-4d0d-a7e1-25710361a027.png)
> 
> 你跟我的邮箱（[suifengingo@163.com](mailto:suifengingo@163.com) )发个消息，我发你链接

您好，能否也发我一份链接，谢谢 2928220566@qq.com

**Comment by WestbrookZero** [comment]
@William9Baker 您好，能否也发我一份链接，谢谢844061529@qq.com
