### ISSUE TITLE
数据集如何放置？

### ISSUE THREAD

**Issue by William9Baker** [CASIA-IVA-Lab/AnomalyGPT#26]
我理解的是MVTec-AD dataset和pre-training data of PandaGPT这两个数据集应该都要下载，那么如何放置呢？我是下面这样放置的，但是训练时候貌似不太对，望指教，谢谢！
data
|---pandagpt4_visual_instruction_data.json
|---images
|-----|----mvtec_anomaly_detection
|----------|-- bottle
|----------|-----|---- ground_truth
|----------|-----|----- test
|----------|-----|----- train
|-----|----images
|-----|-----|----- 000000124934.jpg
|-----|-----|----- 000000257414.jpg

**Comment by William9Baker** [comment]
而且还有个问题，训练时候，MVTec-AD dataset是否也需要针对性地制作对应的'.json'文件，用于文本提示？

**Comment by William9Baker** [comment]
训练时候pre-training data of PandaGPT这个数据集是否为必须的？还是说可以只用MvTec数据集进行训练？

**Comment by FantasticGNU** [comment]
您再仔细对比一下 README 里面的数据集放置方法。PandaGPT 的训练图片直接放在 `data/images` 文件夹里面，images 文件夹和其他数据集的文件夹是并列的。
