### ISSUE TITLE
ValueError: high <= 0

### ISSUE THREAD

**Issue by IESSTTJP** [CASIA-IVA-Lab/AnomalyGPT#30]
运行train_mvtec.sh出现ValueError: high <= 0错误
<img width="166" alt="image" src="https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/123283269/6be3eccd-d391-44b8-864b-7d13f6707151">

**Comment by F-Yuan303** [comment]
请问您是如何解决的？

**Comment by IESSTTJP** [comment]
> 请问您是如何解决的？

把类别里的空白文档删掉就好了

**Comment by F-Yuan303** [comment]
感谢！
