### ISSUE TITLE
Vicuna model无法下载

### ISSUE THREAD

**Issue by Ontheway361** [CASIA-IVA-Lab/AnomalyGPT#31]
有无老铁可以给一个Vicuna model的下载链接或者云盘链接 ？

**Comment by GDUTLinsy** [comment]
Have you found the download link for Vicuna model？

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。

**Comment by GDUTLinsy** [comment]
Can you share with me the weights of the Vicuna model? I applied to MateAI last week but haven't received a response yet.

**Comment by wangwang324** [comment]
> 您好，我已经收到您的邮件，谢谢。

你好，可以分享一下Vicuna model吗?

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。

**Comment by 2022xbing** [comment]
你好，可以分享一下Vicuna model吗?

**Comment by EudicL** [comment]
> 你好，可以分享一下Vicuna model吗?

你好，可以分享一下Vicuna model吗?

**Comment by Celinewxy** [comment]
> 您好，我已经收到您的邮件，谢谢。
你好，可以分享一下Vicuna model吗?

**Comment by tenderzada** [comment]
> 有无老铁可以给一个Vicuna model的下载链接或者云盘链接 ？

你好，可以给我转一下Vicuna model吗?

**Comment by Eren-yeager-zero** [comment]
> 有无老铁可以给一个Vicuna model的下载链接或者云盘链接 ？

您好，请问可以分享一下吗，谢谢

**Comment by yjtlab** [comment]
> 你好，可以分享一下Vicuna model吗，十分感谢?

**Comment by tenderzada** [comment]
我从这里下载LLama的权重（https://huggingface.co/huggyllama/llama-7b/tree/main），然后按作者提供的方法获取到了Vicuna。

**Comment by yjtlab** [comment]
非常感谢hxd

2023-11-27 10:46:07tenderzada ***@***.***>写道：

我从这里下载LLama的权重（https://huggingface.co/huggyllama/llama-7b/tree/main），然后按作者提供的方法获取到了Vicuna。

**Comment by mellody11** [comment]
> 我从这里下载LLama的权重（[https://huggingface.co/huggyllama/llama-7b/tree/main），然后按作者提供的方法获取到了Vicuna。](https://huggingface.co/huggyllama/llama-7b/tree/main%EF%BC%89%EF%BC%8C%E7%84%B6%E5%90%8E%E6%8C%89%E4%BD%9C%E8%80%85%E6%8F%90%E4%BE%9B%E7%9A%84%E6%96%B9%E6%B3%95%E8%8E%B7%E5%8F%96%E5%88%B0%E4%BA%86Vicuna%E3%80%82)
您好，我按作者的方法生成的Vicuna的格式是safetensor，不是此代码要求的bin，请问您有遇到这个问题吗，好像这个问题是最近才出现的，可能是fastchat库进行了修改？

**Comment by qq604395564** [comment]
您好，Vicuna model的权重怎么下载呢，能给个新的下载链接吗

**Comment by Celinewxy** [comment]
> > 您好，我已经收到您的邮件，谢谢。
> 
> 可否分享个链接呢

您好，可以分享个下载链接吗

**Comment by Eren-yeager-zero** [comment]
> > 我从这里下载LLama的权重（[https://huggingface.co/huggyllama/llama-7b/tree/main），然后按作者提供的方法获取到了Vicuna。](https://huggingface.co/huggyllama/llama-7b/tree/main%EF%BC%89%EF%BC%8C%E7%84%B6%E5%90%8E%E6%8C%89%E4%BD%9C%E8%80%85%E6%8F%90%E4%BE%9B%E7%9A%84%E6%96%B9%E6%B3%95%E8%8E%B7%E5%8F%96%E5%88%B0%E4%BA%86Vicuna%E3%80%82)
> > 您好，我按作者的方法生成的Vicuna的格式是safetensor，不是此代码要求的bin，请问您有遇到这个问题吗，好像这个问题是最近才出现的，可能是fastchat库进行了修改？

您好，我也遇到了这个问题，请问您解决了吗？

**Comment by mellody11** [comment]
> > > 我从这里下载LLama的权重（[https://huggingface.co/huggyllama/llama-7b/tree/main），然后按作者提供的方法获取到了Vicuna。](https://huggingface.co/huggyllama/llama-7b/tree/main%EF%BC%89%EF%BC%8C%E7%84%B6%E5%90%8E%E6%8C%89%E4%BD%9C%E8%80%85%E6%8F%90%E4%BE%9B%E7%9A%84%E6%96%B9%E6%B3%95%E8%8E%B7%E5%8F%96%E5%88%B0%E4%BA%86Vicuna%E3%80%82)
> > > 您好，我按作者的方法生成的Vicuna的格式是safetensor，不是此代码要求的bin，请问您有遇到这个问题吗，好像这个问题是最近才出现的，可能是fastchat库进行了修改？
> 
> 您好，我也遇到了这个问题，请问您解决了吗？

这个问题我通过降低transformers的版本解决了，你可以用仓库中requirement.txt中的transformers版本进行转换。

**Comment by Eren-yeager-zero** [comment]
> > > > 我从这里下载LLama的权重（[https://huggingface.co/huggyllama/llama-7b/tree/main），然后按作者提供的方法获取到了Vicuna。](https://huggingface.co/huggyllama/llama-7b/tree/main%EF%BC%89%EF%BC%8C%E7%84%B6%E5%90%8E%E6%8C%89%E4%BD%9C%E8%80%85%E6%8F%90%E4%BE%9B%E7%9A%84%E6%96%B9%E6%B3%95%E8%8E%B7%E5%8F%96%E5%88%B0%E4%BA%86Vicuna%E3%80%82)
> > > > 您好，我按作者的方法生成的Vicuna的格式是safetensor，不是此代码要求的bin，请问您有遇到这个问题吗，好像这个问题是最近才出现的，可能是fastchat库进行了修改？
> > 
> > 
> > 您好，我也遇到了这个问题，请问您解决了吗？
> 
> 这个问题我通过降低transformers的版本解决了，你可以用仓库中requirement.txt中的transformers版本进行转换。

万分感谢！

**Comment by EddieEduardo** [comment]
可以分享一个Vicuna链接嘛，上面的打不开了， 感谢🤝

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。

**Comment by EddieEduardo** [comment]
你好，请问这个链接里的权重下载后还需要转换吗？https://huggingface.co/huggyllama/llama-7b/tree/main

**Comment by anshiwangwang** [comment]
您好，请问从[https://huggingface.co/huggyllama/llama-7b/tree/main]下载的的权重还需要和作者说的增量权重进行合并吗？

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。

**Comment by YuhangPan79** [comment]
> 您好，我已经收到您的邮件，谢谢。

你好，可以分享一下Vicuna model吗?

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。

**Comment by LinPengyue** [comment]
你好，可以分享一下Vicuna模型吗？

**Comment by fpgboy** [comment]
> 您好，我已经收到您的邮件，谢谢。

请问您可以分享一下Vicuna model的下载链接吗？

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。
