### ISSUE TITLE
咨询文章ablation study 结果

### ISSUE THREAD

**Issue by MaitaYuki** [CASIA-IVA-Lab/AnomalyGPT#32]
作者，
感谢你们出色的工作！
有个问题咨询一下。在你们文章表四的结果中，如果只用Decoder, 和Decoder 加上prompt learner及LLM 的设置对比的话，在MVTec集上Image-AUC结果只有0.3的差距。语言的加入帮助不显著。这里的只用Decoder在MVTec上unsupervised设置，是指只用所有的正样本来训练，没用伪负样本训练，对吧？另外，如果同patch core文章中的99.1%比，你们的结果还是差了一点。可有什么设定能超过99.1，例如unsupervised和few-shot结合起来有可能吗？

期待你们的恢复。
谢谢！

**Comment by FantasticGNU** [comment]
1. 语言的加入带来的不仅仅是性能的提升，相关内容在 Issue #9 中有详细的解释。
2. unsupervised 设置指的是不使用真实异常样本，我们使用了训练集中的真实正常样本和合成的模拟异常样本。
3. patchCore 采用了“一类一个模型”的设置，为每一类别物体单独训练一个模型，得到的模型只能对这类物品进行异常检测。而我们的方法对于任意类别物品使用同一个模型，而且可以 few-shot 迁移，所以 AUC 指标要稍低一些。
