### ISSUE TITLE
 请教如何使用LLaMA2

### ISSUE THREAD

**Issue by weiweinorth** [CASIA-IVA-Lab/AnomalyGPT#33]
作者：
你们好！
我下载不到LLaMA。请问用LLaMA2，应该也可以吧？只是用LLaMA2，Vicuna的版本也得用对应LLaMA2的，对吗？我查到lmsys/vicuna-7b-v1.5是fine-tuning Llama 2得到的，那我下载这个版本可以吗（https://huggingface.co/lmsys/vicuna-7b-v1.5）？下载vicuna-7b-v1.5这个版本，是不是就不用下载delta weights of vicuna， 也不用Combine the Weights，因为它就是完整的weights of vicuna， 对吗？直接把vicuna-7b-v1.5的weight放在/vicuna_ckpt/7b_v0/下面。其它步骤都按你INSTRUCTION做，可行吗？
谢谢答复！

**Comment by FantasticGNU** [comment]
llama 和 llama2 在数据格式（起止符号等）上有一些区别，我们的方法只针对 Vicuna v0 做了图文对齐，如果使用 llama2 和对应的 Vicuna 版本，需要修改代码中数据格式的部分以符合 llama2 的设置，并重新训练通用图文对齐部分和异常检测任务部分

**Comment by twmht** [comment]
> 需要修改代码中数据格式的部分以符合 llama2 的设置，并重新训练通用图文对齐部分和异常检测任务部分
這邊有 training code 嗎?
