### ISSUE TITLE
Image loading classification problem without  mask during training

### ISSUE THREAD

**Issue by GY123123** [CASIA-IVA-Lab/AnomalyGPT#35]
![2023-10-21 10-59-19屏幕截图](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/50736488/cfac2d94-bad1-4e2c-baf8-912c4b187a3a)

训练时加载无mask的图像de分类问题

**Comment by FantasticGNU** [comment]
没有 mask 的是 pandagpt 原来的训练数据中的图像，这部分图像没有类别信息，所以统一使用 'object'

**Comment by GY123123** [comment]
那如何加载有标签的图像的无mask分类

**Comment by FantasticGNU** [comment]
仿照上面有 mask 的数据的格式，传入 class_name，然后使用 class_name 替换此处的 'object' 即可

**Comment by GY123123** [comment]
感谢回答！运行成功
