### ISSUE TITLE
anomaly image-text data

### ISSUE THREAD

**Issue by iakRulan** [CASIA-IVA-Lab/AnomalyGPT#37]
作者你好，我想请问文中的“anomaly image-text data”是指MVTec-AD和VisA数据集的文本描述吗，我并没有发现数据集中有类似“pandagpt4_visual_instruction_data.json”这种描述文件的

**Comment by FantasticGNU** [comment]
文中的“anomaly image-text data” 指的是在 Section 3.3 中提到的模拟异常图像和问答数据
