### ISSUE TITLE
Anomaly Simulation

### ISSUE THREAD

**Issue by IESSTTJP** [CASIA-IVA-Lab/AnomalyGPT#39]
您好，我想问一下Anomaly Simulation这部分模拟的异常数据在框架和代码中哪里体现的
<img width="391" alt="image" src="https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/123283269/1f14ea14-5462-483e-9152-aca0182a71e1">

**Comment by FantasticGNU** [comment]
模拟的异常数据是用来训练 image decoder 和 prompt learner 的，即在训练期间使用正常数据和模拟的异常数据作为 query image 输入到图中的框架里，对模型进行训练
