### ISSUE TITLE
unable to find hostfile，will proceed with training with local resources only

### ISSUE THREAD

**Issue by Wangjinhong1998** [CASIA-IVA-Lab/AnomalyGPT#41]
![9e655b2d7747d484d3a6fdc4993de0f](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/83818126/9aa338ad-b5c9-487f-98d5-00288dfe006e)

在尝试进行训练时候，train_mvtec遇到这个，请问这个是什么原因呢？需要怎么做或者修改？

**Comment by FantasticGNU** [comment]
这个意思是现在是只在本地单机训练，如果不需要多个节点一起训练的话可以忽略这条 WARNING

**Comment by Wangjinhong1998** [comment]
> 这个意思是现在是只在本地单机训练，如果不需要多个节点一起训练的话可以忽略这条 WARNING

嗯嗯，但是我是放服务器上后，按原原作者的步骤弄得，这个好像是服务器和分布式训练相关的问题吗，请问我接下来该怎么正常运行

**Comment by Eren-yeager-zero** [comment]
> ![9e655b2d7747d484d3a6fdc4993de0f](https://private-user-images.githubusercontent.com/83818126/281730460-9aa338ad-b5c9-487f-98d5-00288dfe006e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzMzMTcsIm5iZiI6MTcwMTUzMzAxNywicGF0aCI6Ii84MzgxODEyNi8yODE3MzA0NjAtOWFhMzM4YWQtYjVjOS00ODdmLTk4ZDUtMDAyODhkZmUwMDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE2MDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjQxZDMwMTIyMDRmYzY1MDJlZWEzMTdlM2MwMzA3NTNlY2ViY2U4MWUwZWJlZjI4MjQwNThkNGM5ZjBlNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CuGBv-5DsZsamt8ij2zw4KhJWYS2ghFp1Y-tjHmwRPg)
> 
> 在尝试进行训练时候，train_mvtec遇到这个，请问这个是什么原因呢？需要怎么做或者修改？

您好，请问您解决了吗，感谢！

**Comment by maoning123ab** [comment]
请问您有解决办法吗，我也是在服务器上出现了这种情况
