### ISSUE TITLE
用作者提供得预训练模型运行web_demo.py时，出现了答非所问和重复的回答

### ISSUE THREAD

**Issue by zkh123456789** [CASIA-IVA-Lab/AnomalyGPT#42]
如题。。。如图。。。。
![1](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/55131043/cdc6cac1-0338-4873-bee0-ded239dc83f6)
![2](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/55131043/7a9c6c90-cd0f-4f87-b52f-fd2a220d2a2c)

**Comment by FantasticGNU** [comment]
输入普通图片，模型可以正常对话吗？看起来 AnomalyGPT 部分的权重是正确加载了，但是不确定 Vicuna 和 PandaGPT 部分的权重有没有正确加载。并且请确认一下我们使用的 Vicuna 应该是 v0 版本的，v1 版本的 Vicuna 修改了数据格式，可能会有问题。
