### ISSUE TITLE
训练报错 [ERROR] [launch.py:320:sigkill_handler]

### ISSUE THREAD

**Issue by Fritzyuan** [CASIA-IVA-Lab/AnomalyGPT#43]
作者你好，我在训练时出现了下面的问题，请问应该用什么办法解决？谢谢

root@C.7517456:/workspace/AnomalyGPT/code$ bash ./scripts/train_mvtec.sh 
Setting ds_accelerator to cuda (auto detect)                                                          
[2023-11-13 16:57:43,920] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.                                                           
[2023-11-13 16:57:43,966] [INFO] [runner.py:555:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=28400 --en
able_each_rank_log=None train_mvtec.py --model openllama_peft --stage 1 --imagebind_ckpt_path ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth --vicuna_ckpt_path ../pretrained_ckpt/vicuna_ckpt/7b_v0/ 
--delta_ckpt_path ../pretrained_ckpt/pandagpt_ckpt/7b/pytorch_model.pt --max_tgt_len 1024 --data_path ../data/pandagpt4_visual_instruction_data.json --image_root_path ../data/images/ --save_path ./ckpt/tr
ain_mvtec/ --log_path ./ckpt/train_mvtec/log_rest/                                                    
Setting ds_accelerator to cuda (auto detect)                                                                                                                                                                
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.13.4-1+cuda11.7                                                                                                
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.13.4-1                                                                                                             
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.13.4-1                         
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev       
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7 
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7                                                                                              [15/1862]
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2                                                                                                                    
[2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.13.4-1                                                                                                                 
[2023-11-13 16:57:45,547] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1]}          
[2023-11-13 16:57:45,547] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=2, node_rank=0                                                                                                              
[2023-11-13 16:57:45,547] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})                                                                                
[2023-11-13 16:57:45,547] [INFO] [launch.py:163:main] dist_world_size=2                               
[2023-11-13 16:57:45,547] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1    

Setting ds_accelerator to cuda (auto detect)                                                                                                                                                                
Setting ds_accelerator to cuda (auto detect)                                                          
/opt/conda/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules di
rectly from transformers.integrations                                                                                                                                                                       
  warnings.warn(                                                                                      
/opt/conda/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules di
rectly from transformers.integrations                                                                                                                                                                       
  warnings.warn(                                                                                                                                                                                            
/opt/conda/lib/python3.10/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in th
e future. Please use the 'torchvision.transforms.functional' module instead.                                                                                                                                
  warnings.warn(                                                                                      
/opt/conda/lib/python3.10/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in th
e future. Please use the 'torchvision.transforms.functional' module instead.                                                                                                                                
  warnings.warn(                                                                                                                                                                                            
/opt/conda/lib/python3.10/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in t
he future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(                                                                                      
/opt/conda/lib/python3.10/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in t
he future. Please use the 'torchvision.transforms' module instead.      
  warnings.warn(                                                                                                                                                                                            
[!] load base configuration: config/base.yaml                                                         
[!] load configuration from config/openllama_peft.yaml                                                                                                                                                      
[2023-11-13 16:57:53,230] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-11-13 16:57:53,230] [INFO] [comm.py:594:init_distributed] cdb=None                                                                                                                                    
[!] load base configuration: config/base.yaml
[!] load configuration from config/openllama_peft.yaml                                                
[2023-11-13 16:57:53,259] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-11-13 16:57:53,259] [INFO] [comm.py:594:init_distributed] cdb=None                 
[2023-11-13 16:57:53,259] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[!] collect 161151 samples for training                                                               
[!] collect 161151 samples for training                                                                                                                                                                     
Initializing visual encoder from ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth ...                                                                                                                   
Initializing visual encoder from ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth ...                                                                                                                   
Visual encoder initialized.                                                                           
Initializing language decoder from ../pretrained_ckpt/vicuna_ckpt/7b_v0/ ...                                                                                                                                
Visual encoder initialized.                                                                                                                                                                                 
Initializing language decoder from ../pretrained_ckpt/vicuna_ckpt/7b_v0/ ...                                                                                                                                
[2023-11-13 16:59:54,760] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 9439
[2023-11-13 16:59:54,783] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 9440
[2023-11-13 16:59:55,650] [ERROR] [launch.py:320:sigkill_handler] ['/opt/conda/bin/python', '-u', 'train_mvtec.py', '--local_rank=1', '--model', 'openllama_peft', '--stage', '1', '--imagebind_ckpt_path', 
'../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth', '--vicuna_ckpt_path', '../pretrained_ckpt/vicuna_ckpt/7b_v0/', '--delta_ckpt_path', '../pretrained_ckpt/pandagpt_ckpt/7b/pytorch_model.pt', '--max_t
gt_len', '1024', '--data_path', '../data/pandagpt4_visual_instruction_data.json', '--image_root_path', '../data/images/', '--save_path', './ckpt/train_mvtec/', '--log_path', './ckpt/train_mvtec/log_rest/'
] exits with return code = -9

**Comment by FantasticGNU** [comment]
大概率是显存不够导致的，训练大概需要24G显存

**Comment by Eren-yeager-zero** [comment]
> 作者你好，我在训练时出现了下面的问题，请问应该用什么办法解决？谢谢
> 
> root@C.7517456:/workspace/AnomalyGPT/code$ bash ./scripts/train_mvtec.sh Setting ds_accelerator to cuda (auto detect) [2023-11-13 16:57:43,920] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only. [2023-11-13 16:57:43,966] [INFO] [runner.py:555:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=28400 --en able_each_rank_log=None train_mvtec.py --model openllama_peft --stage 1 --imagebind_ckpt_path ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth --vicuna_ckpt_path ../pretrained_ckpt/vicuna_ckpt/7b_v0/ --delta_ckpt_path ../pretrained_ckpt/pandagpt_ckpt/7b/pytorch_model.pt --max_tgt_len 1024 --data_path ../data/pandagpt4_visual_instruction_data.json --image_root_path ../data/images/ --save_path ./ckpt/tr ain_mvtec/ --log_path ./ckpt/train_mvtec/log_rest/ Setting ds_accelerator to cuda (auto detect) [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.13.4-1+cuda11.7 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.13.4-1 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.13.4-1 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7 [15/1862] [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.13.4-1 [2023-11-13 16:57:45,547] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1]} [2023-11-13 16:57:45,547] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=2, node_rank=0 [2023-11-13 16:57:45,547] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]}) [2023-11-13 16:57:45,547] [INFO] [launch.py:163:main] dist_world_size=2 [2023-11-13 16:57:45,547] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1
> 
> Setting ds_accelerator to cuda (auto detect) Setting ds_accelerator to cuda (auto detect) /opt/conda/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules di rectly from transformers.integrations warnings.warn( /opt/conda/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules di rectly from transformers.integrations warnings.warn( /opt/conda/lib/python3.10/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in th e future. Please use the 'torchvision.transforms.functional' module instead. warnings.warn( /opt/conda/lib/python3.10/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in th e future. Please use the 'torchvision.transforms.functional' module instead. warnings.warn( /opt/conda/lib/python3.10/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in t he future. Please use the 'torchvision.transforms' module instead. warnings.warn( /opt/conda/lib/python3.10/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in t he future. Please use the 'torchvision.transforms' module instead. warnings.warn( [!] load base configuration: config/base.yaml [!] load configuration from config/openllama_peft.yaml [2023-11-13 16:57:53,230] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented [2023-11-13 16:57:53,230] [INFO] [comm.py:594:init_distributed] cdb=None [!] load base configuration: config/base.yaml [!] load configuration from config/openllama_peft.yaml [2023-11-13 16:57:53,259] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented [2023-11-13 16:57:53,259] [INFO] [comm.py:594:init_distributed] cdb=None [2023-11-13 16:57:53,259] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl [!] collect 161151 samples for training [!] collect 161151 samples for training Initializing visual encoder from ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth ... Initializing visual encoder from ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth ... Visual encoder initialized. Initializing language decoder from ../pretrained_ckpt/vicuna_ckpt/7b_v0/ ... Visual encoder initialized. Initializing language decoder from ../pretrained_ckpt/vicuna_ckpt/7b_v0/ ... [2023-11-13 16:59:54,760] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 9439 [2023-11-13 16:59:54,783] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 9440 [2023-11-13 16:59:55,650] [ERROR] [launch.py:320:sigkill_handler] ['/opt/conda/bin/python', '-u', 'train_mvtec.py', '--local_rank=1', '--model', 'openllama_peft', '--stage', '1', '--imagebind_ckpt_path', '../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth', '--vicuna_ckpt_path', '../pretrained_ckpt/vicuna_ckpt/7b_v0/', '--delta_ckpt_path', '../pretrained_ckpt/pandagpt_ckpt/7b/pytorch_model.pt', '--max_t gt_len', '1024', '--data_path', '../data/pandagpt4_visual_instruction_data.json', '--image_root_path', '../data/images/', '--save_path', './ckpt/train_mvtec/', '--log_path', './ckpt/train_mvtec/log_rest/' ] exits with return code = -9

您好，我在训练时遇到了跟您类似的错误，但是我的显存是够的，请问您最后解决了吗？万分感谢

**Comment by Fritzyuan** [comment]
> > 作者你好，我在训练时出现了下面的问题，请问应该用什么办法解决？谢谢
> > root@C.7517456:/workspace/AnomalyGPT/code$ bash ./scripts/train_mvtec.sh Setting ds_accelerator to cuda (auto detect) [2023-11-13 16:57:43,920] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only. [2023-11-13 16:57:43,966] [INFO] [runner.py:555:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=28400 --en able_each_rank_log=None train_mvtec.py --model openllama_peft --stage 1 --imagebind_ckpt_path ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth --vicuna_ckpt_path ../pretrained_ckpt/vicuna_ckpt/7b_v0/ --delta_ckpt_path ../pretrained_ckpt/pandagpt_ckpt/7b/pytorch_model.pt --max_tgt_len 1024 --data_path ../data/pandagpt4_visual_instruction_data.json --image_root_path ../data/images/ --save_path ./ckpt/tr ain_mvtec/ --log_path ./ckpt/train_mvtec/log_rest/ Setting ds_accelerator to cuda (auto detect) [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.13.4-1+cuda11.7 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.13.4-1 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.13.4-1 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.13.4-1+cuda11.7 [15/1862] [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2 [2023-11-13 16:57:45,547] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.13.4-1 [2023-11-13 16:57:45,547] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1]} [2023-11-13 16:57:45,547] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=2, node_rank=0 [2023-11-13 16:57:45,547] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]}) [2023-11-13 16:57:45,547] [INFO] [launch.py:163:main] dist_world_size=2 [2023-11-13 16:57:45,547] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1
> > Setting ds_accelerator to cuda (auto detect) Setting ds_accelerator to cuda (auto detect) /opt/conda/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules di rectly from transformers.integrations warnings.warn( /opt/conda/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules di rectly from transformers.integrations warnings.warn( /opt/conda/lib/python3.10/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in th e future. Please use the 'torchvision.transforms.functional' module instead. warnings.warn( /opt/conda/lib/python3.10/site-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in th e future. Please use the 'torchvision.transforms.functional' module instead. warnings.warn( /opt/conda/lib/python3.10/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in t he future. Please use the 'torchvision.transforms' module instead. warnings.warn( /opt/conda/lib/python3.10/site-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in t he future. Please use the 'torchvision.transforms' module instead. warnings.warn( [!] load base configuration: config/base.yaml [!] load configuration from config/openllama_peft.yaml [2023-11-13 16:57:53,230] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented [2023-11-13 16:57:53,230] [INFO] [comm.py:594:init_distributed] cdb=None [!] load base configuration: config/base.yaml [!] load configuration from config/openllama_peft.yaml [2023-11-13 16:57:53,259] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented [2023-11-13 16:57:53,259] [INFO] [comm.py:594:init_distributed] cdb=None [2023-11-13 16:57:53,259] [INFO] [comm.py:625:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl [!] collect 161151 samples for training [!] collect 161151 samples for training Initializing visual encoder from ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth ... Initializing visual encoder from ../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth ... Visual encoder initialized. Initializing language decoder from ../pretrained_ckpt/vicuna_ckpt/7b_v0/ ... Visual encoder initialized. Initializing language decoder from ../pretrained_ckpt/vicuna_ckpt/7b_v0/ ... [2023-11-13 16:59:54,760] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 9439 [2023-11-13 16:59:54,783] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 9440 [2023-11-13 16:59:55,650] [ERROR] [launch.py:320:sigkill_handler] ['/opt/conda/bin/python', '-u', 'train_mvtec.py', '--local_rank=1', '--model', 'openllama_peft', '--stage', '1', '--imagebind_ckpt_path', '../pretrained_ckpt/imagebind_ckpt/imagebind_huge.pth', '--vicuna_ckpt_path', '../pretrained_ckpt/vicuna_ckpt/7b_v0/', '--delta_ckpt_path', '../pretrained_ckpt/pandagpt_ckpt/7b/pytorch_model.pt', '--max_t gt_len', '1024', '--data_path', '../data/pandagpt4_visual_instruction_data.json', '--image_root_path', '../data/images/', '--save_path', './ckpt/train_mvtec/', '--log_path', './ckpt/train_mvtec/log_rest/' ] exits with return code = -9
> 
> 您好，我在训练时遇到了跟您类似的错误，但是我的显存是够的，请问您最后解决了吗？万分感谢

你好，我后来发现是内存不够，还了一台内存更大的机器解决了问题
