### ISSUE TITLE
运行./scripts/train_mvtec.sh 进行训练的时候报错

### ISSUE THREAD

**Issue by 2132660698** [CASIA-IVA-Lab/AnomalyGPT#5]
报错信息如下，我的机器上8*A100 40G：
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/f486eb7c-c2b9-43c5-9362-7e4e35dd79a8)

**Comment by FantasticGNU** [comment]
我们在最新的代码中已经修复了这个问题，为您带来的不便深表歉意，感谢指正！
