### ISSUE TITLE
setup更改成1-shot,2-shot和4-shot的话是要在代码哪些地方进行修改

### ISSUE THREAD

**Issue by IESSTTJP** [CASIA-IVA-Lab/AnomalyGPT#56]
setup更改成1-shot,2-shot和4-shot的话是要在代码哪些地方进行修改

**Comment by FantasticGNU** [comment]
在运行 test_*.py 的时候使用命令行参数设置，参考 [test_mvtec.py#L13](https://github.com/CASIA-IVA-Lab/AnomalyGPT/blob/main/code/test_mvtec.py#L13)，运行时指定 --k-shot 2 或 --k-shot 4 即可
