### ISSUE TITLE
运行./scripts/train_visa.sh 训练的时候报错

### ISSUE THREAD

**Issue by 2132660698** [CASIA-IVA-Lab/AnomalyGPT#6]
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/eefbd766-9220-4dd8-8a01-5a0e58c6381d)
应该是这个地方报的错误：
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/b8fdb3ef-bc17-4169-a540-36e19efa3fe7)

应该是这个地方少返回
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/b9892515-097e-4992-be33-ca87c5964be4)

**Comment by FantasticGNU** [comment]
我们在最新的代码中已经修复了这个问题，为您带来的不便深表歉意，感谢指正！
