### ISSUE TITLE
用自己数据集微调的时候，需要将pandagpt4_visual_instruction_data.json和images放上去吗

### ISSUE THREAD

**Issue by hexiajunu** [CASIA-IVA-Lab/AnomalyGPT#60]
为什么自己微调的时候，epoch跑了一两轮后就自己结束了

**Comment by FantasticGNU** [comment]
pandagpt的数据是用来数据平衡，防止过拟合下游数据集和灾难性遗忘的，建议放上去一起训练。如果不用pandagpt的数据，需要修改一下 train_xxx.py 里面数据读取部分的代码
