### ISSUE TITLE
运行web_demo.py文件之后，为什么demo演示效果很糟糕

### ISSUE THREAD

**Issue by xtuxgq** [CASIA-IVA-Lab/AnomalyGPT#66]
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/114065073/d2c42e96-0bff-44dc-9ebb-286a6239b2be)

**Comment by FantasticGNU** [comment]
可能是在合并 LLAMA 和 Vicuna 权重的时候出现了问题，也可能是在组合 Vicuna 权重和 PandaGPT 的权重的过程中出现了问题；请首先确认合并后的 Vicuna 拥有正常的 LLM 能力，然后确认合并后的 PandaGPT 拥有正常的多模态对话能力，最后再确认合并 AnomalyGPT 的参数后模型拥有异常检测能力。

**Comment by xtuxgq** [comment]
> 可能是在合并 LLAMA 和 Vicuna 权重的时候出现了问题，也可能是在组合 Vicuna 权重和 PandaGPT 的权重的过程中出现了问题；请首先确认合并后的 Vicuna 拥有正常的 LLM 能力，然后确认合并后的 PandaGPT 拥有正常的多模态对话能力，最后再确认合并 AnomalyGPT 的参数后模型拥有异常检测能力。

那请问为什么在运行test_mvtec的时候会出现“A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.” 这样的提示，请问要怎么修改？

**Comment by xtuxgq** [comment]
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/114065073/28ba5005-cc62-4431-811b-59e3c3551b93)

**Comment by ES6JimHsieh** [comment]
> 可能是在合并 LLAMA 和 Vicuna 权重的时候出现了问题，也可能是在组合 Vicuna 权重和 PandaGPT 的权重的过程中出现了问题；请首先确认合并后的 Vicuna 拥有正常的 LLM 能力，然后确认合并后的 PandaGPT 拥有正常的多模态对话能力，最后再确认合并 AnomalyGPT 的参数后模型拥有异常检测能力。

你好，我在运行web_demo.py文件也遇到相同的问题，想问一下要怎么确认合并后的 Vicuna 拥有正常的 LLM 能力?

**Comment by TinkGrind** [comment]
直接用vicnua v1.1就可以正常运行，已有合并好的
