### ISSUE TITLE
在“test_mvtec.py”文件中的arguments “--round”是什么意思

### ISSUE THREAD

**Issue by lalisa2020** [CASIA-IVA-Lab/AnomalyGPT#69]
在“test_mvtec.py”文件中的arguments “--round”是什么意思，是多轮对话的意思吗，paper里面的Table 2的结果“--round”设置的多少呢？

**Comment by FantasticGNU** [comment]
--round 参数是用于在少样本设置中，选取不同的正常样本的。这个参数用于在不同的正常参考样本下进行多轮实验，从而得到少样本设置中的最终实验结果。Table 2 的结果是在随机选取的 5 个 round 值下的平均结果。
