### ISSUE TITLE
更新今天最新代码后，训练还是报错，请再看看，谢谢。

### ISSUE THREAD

**Issue by 2132660698** [CASIA-IVA-Lab/AnomalyGPT#7]
更新今天最新代码后，./scripts/train_visa.sh 和./scripts/train_mvtec.sh 还是报错，错误应该是一样的，请再看一下，谢谢。
![1693549954602_86114164-EF62-4010-B0D3-0F956B78BA15](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/fa36e763-736a-4ac2-9011-3d1ef36a753e)

![5af828755b0bf64f51100bcad8090886](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/4c46d59b-147e-441a-b99a-d71b4b64360f)

**Comment by 2132660698** [comment]
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/2027b794-8b0f-442b-af4b-0da61718e59c)
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/4af0486e-99bf-4d67-8b33-b69d8784a624)

**Comment by FantasticGNU** [comment]
我这边刚试了一下是正常运行的，python 版本是 3.8.17，cuda 版本是 11.7，GPU 是 RTX 3090，您的 python 和 cuda 版本是多少呢？

**Comment by FantasticGNU** [comment]
貌似是 deepspeed 的 BUG，您可以参照这个链接 https://github.com/microsoft/DeepSpeed/issues/4188 尝试解决一下

**Comment by 2132660698** [comment]
应该是deepspeed 的问题，把deepspeed 改成0.9.3版本后，能跑起来了，跑到保存点的时候报错了。
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/94035926/d9ebf6e5-80d3-4397-93f0-895068680c17)

能把你的环境各个包的版本贴一下吗？

**Comment by 2132660698** [comment]
感谢，问题解决了，我把pytorch版本从2.0.1降低到torch=1.13.1、torchaudio=0.13.1、torchvision=0.14.1后就可以顺利保存了。

**Comment by zkh123456789** [comment]
> 感谢，问题解决了，我把pytorch版本从2.0.1降低到torch=1.13.1、torchaudio=0.13.1、torchvision=0.14.1后就可以顺利保存了。

兄弟 ， 我和你一样  一开始用2.0.1  保存模型 报错 但是用1.13.1又会报错“AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'”   兄弟有没有啥解决方法==
