### ISSUE TITLE
关于文章实验中的table3

### ISSUE THREAD

**Issue by xtuxgq** [CASIA-IVA-Lab/AnomalyGPT#72]
我想请问一下作者，为什么在做Few-shot对比实验的时候要和patchcore比，但是在无监督异常检测实验中却不和patchcore比呢？

**Comment by FantasticGNU** [comment]
因为在无监督设置下， PatchCore 遵循 “一类一个模型” 的训练范式，对于 mvtec 中的 15 个类别的模型，他需要训练 15 个模型，而我们的方法只需要一个模型，所以我们选择了使用相同设置的一个模型可以适用于多个类别的方法进行比较。

而在 Few-shot 设置下，PatchCore 可以不经过训练，直接将少量参考图像的所有 patch 特征全都存到 memory bank 里面，这种设置与我们的方法是相同的，都是不经过参数训练直接在新类别上进行检测，所以我们在 Few-shot 实验的时候和 PatchCore 比较了

**Comment by xtuxgq** [comment]
还想请问一下作者，为什么不在Visa这个数据集上做无监督异常检测实验呢？而仅仅只是做了few-shot实验？

**Comment by FantasticGNU** [comment]
因为我们对比的那几个方法只提供了在 mvtec 上的实验结果

**Comment by xtuxgq** [comment]
作者的实验结果我已经基本复现完成，没有任何问题，但是我尝试在Visa数据集上做无监督异常检测，却得出以下结果。这是因为Anomalygpt不适合应用于Visa这个数据集嘛？
![image](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/114065073/fc70c279-a7d3-44a8-a51f-8b02f67569bc)
