### ISSUE TITLE
运行web_demo.py，出现提示：To create a public link, set `share=True` in `launch()`. 程序停住不动，请问如何解决？谢谢

### ISSUE THREAD

**Issue by ysm022** [CASIA-IVA-Lab/AnomalyGPT#94]
下载llama-7b和vicuna-7b-delta-v1.1后，合并部署完成。运行python web_demo.py，停在To create a public link, set `share=True` in `launch()`.不动了，请问什么情况？如何解决？谢谢
![1](https://github.com/CASIA-IVA-Lab/AnomalyGPT/assets/20719469/ee5f095e-bbb2-42aa-a8bb-8d5692c73108)

**Comment by qazqaz12378** [comment]
这运行成功啦。

**Comment by ysm022** [comment]
> 这运行成功啦。

是么？怎么调用对话？麻烦指点一下，谢谢

**Comment by qazqaz12378** [comment]
127.0.0.1:7860 这个就是访问的地址。

**Comment by ysm022** [comment]
> 127.0.0.1:7860 这个就是访问的地址。

谢谢

**Comment by cwczyj** [comment]
> 下载llama-7b和vicuna-7b-delta-v1.1后，合并部署完成。运行python web_demo.py，停在To create a public link, set `share=True` in `launch()`.不动了，请问什么情况？如何解决？谢谢 ![1](https://private-user-images.githubusercontent.com/20719469/333492908-ee5f095e-bbb2-42aa-a8bb-8d5692c73108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzIyMTEsIm5iZiI6MTcyODk3MTkxMSwicGF0aCI6Ii8yMDcxOTQ2OS8zMzM0OTI5MDgtZWU1ZjA5NWUtYmJiMi00MmFhLWE4YmItOGQ1NjkyYzczMTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA1NTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZDljZDViZmNmNzgxYzllMWQ4NWExYzk2YWZlN2VjNmYzM2ZmMThkYWYxYTk3N2MwYmU2NDYxMjZhMGU0ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JH9wTiw1O44bRQtMd09CIyXxPInmvOpjvAyRzIlkKHo)

请问您的llama-7b和vicuna-7b-delta-v1.1都是在哪里下载的？

**Comment by cwczyj** [comment]
> > 下载llama-7b和vicuna-7b-delta-v1.1后，合并部署完成。运行python web_demo.py，停在To create a public link, set `share=True` in `launch()`.不动了，请问什么情况？如何解决？谢谢 ![1](https://private-user-images.githubusercontent.com/20719469/333492908-ee5f095e-bbb2-42aa-a8bb-8d5692c73108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzIyMTEsIm5iZiI6MTcyODk3MTkxMSwicGF0aCI6Ii8yMDcxOTQ2OS8zMzM0OTI5MDgtZWU1ZjA5NWUtYmJiMi00MmFhLWE4YmItOGQ1NjkyYzczMTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA1NTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZDljZDViZmNmNzgxYzllMWQ4NWExYzk2YWZlN2VjNmYzM2ZmMThkYWYxYTk3N2MwYmU2NDYxMjZhMGU0ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JH9wTiw1O44bRQtMd09CIyXxPInmvOpjvAyRzIlkKHo)
> 
> 请问您的llama-7b和vicuna-7b-delta-v1.1都是在哪里下载的？

https://github.com/CASIA-IVA-Lab/AnomalyGPT/issues/66#issuecomment-2066080222 刚刚测试可用

**Comment by zhong110020** [comment]
遇到跟你一样的问题，127.0.0.1:7860 这个访问地址打不开，请问怎么解决？
